### ISSUE TITLE
errorFlag card class initialized?

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/p12345vls-Decks-of-Cards#12]
In the CARD class, in the two different constructors, should we initialize errorFlag boolean instance variable to false?

**Comment by mdoussias** [comment]
Not sure how to interpret the spec as below:  
"Card(char value, Suit suit) - The constructor should call the proper mutator(s).  Overload this to cope with a client that wants to instantiate without parameters and use 'A' and 'spades' as the default value and suit when not supplied.  Provide at least two constructors -- no parameters and all parameters -- or more if you wish.  **Because we have the errorFlag member, the constuctor (via the mutator), can set that member when it gets bad data**; it does not have to assign default values upon receipt of bad data.  This is a new technique for us.  Again, default card (no parameters passed) is the ('A', spades)."

**Comment by hmason55** [comment]
@mdoussias 
When defined as:
`boolean errorFlag;`

errorFlag is already false by default.

As for the spec:
> Because we have the errorFlag member, the constuctor (via the mutator), can set that member when it gets bad data;

I assume this refers to what was done here in the mutator method `boolean set(char value, Suit suit)`:

`if (!isValid(value, suit))`
`{`
`   errorFlag = true;`
`   return false;`
` }`
`this.suit = suit;`
`this.value = value;`
`errorFlag = false;`
`return true;`

errorFlag is being set each time before returning another value. The return value is telling us whether the mutator call was successful, and the errorFlag is used later to tell us if there is some other general error.

**Comment by mdoussias** [comment]
Sounds good.  I will close this issue.
