### ISSUE TITLE
Deck class deals 51 cards instead of 52

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/p12345vls-Decks-of-Cards#15]
I noticed that the deck class isn't dealing the last card in the deck. In an unsorted deck this would be the the 2 of Clubs. You can check this by running the main function with the option of 1 deck or testDeck() with the option of 1 deck

**Comment by hmason55** [comment]
I'll look into it when I get home, I have a feeling it's either the dealCard or allocateMasterPack methods.

**Comment by hmason55** [comment]
Actually I think this may be the issue, in the Deck method getNumCards change from this:
`public int getNumCards()
{
      return topCard;
 }`

To this:
`public int getNumCards()
 {
      return topCard+1;
 }`

getNumCards is supposed to return the number of cards, not the index of the top card.

**Comment by Mcghee-Jake** [comment]
That may be part of the issue, but I just tested making that change alone to the code and it throws the program into an infinite loop ¯\_(ツ)_/¯

**Comment by hmason55** [comment]
Ouch haha, yeah I'm not really sure then. If the deck size is 51 it's probably allocateMasterPack, if the length is 52 then it's probably an issue with dealCard. 
I can try doing some tests when I get home around 6pm if it persists.

**Comment by hmason55** [comment]
@Mcghee-Jake So I found the issue. If you take a look at the Hand class, there is a constant called MAX_CARDS and it is set to 50. So when you try to deal 52 cards from the deck into a hand it stops at 50 because the hand is full. I also discovered that the A of clubs is missing too since it should be just after the 2 of clubs.
