### ISSUE TITLE
Deck Class

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/p12345vls-Decks-of-Cards#2]
>  A class that represents the source of the cards for dealing and, as the game progresses, the place from which players can receive new cards (say, as they pick cards "from the deck" or when future hands are to be dealt from the same deck).  Recall this picture, which relates the Deck to the various Hands that it creates through the process called "dealing".

### Public Static Class Contants

- [x] Define a **public final int value like MAX_CARDS**, and initialize it to allow a maximum of six packs (6×52 cards).

### Private Static Member Data
- [x] **Card[] masterPack**

### Private Member Data
- [x] **Card[] cards**
- [x] **int topCard**
- [x] **int numPacks**

### Public Methods
- [x] **Deck(int numPacks)** 
    - [x] a constructor that populates the arrays and assigns initial values to members.  
    - [x] Overload so that if no parameters are passed, 1 pack is assumed.
- [x] **void init(int numPacks)** - re-populate cards[] with the standard 52 × numPacks cards.  We should not repopulate the static array, masterPack[], since that was done once, in the (first-invoked) constructor and  never changes.
- [x] **void shuffle()** - mixes up the cards with the help of the standard random number generator.
- [x] **Card dealCard()** - returns and removes the card in the top occupied position of cards[].
- [x] An **accessor** for the **int, topCard (no mutator.)**
- [x] **Card inspectCard(int k)** - Accessor for an individual card.  Returns a card with errorFlag = true if k is bad.

### Private Methods
- [x] **static void allocateMasterPack()** - this is a private method that will be called by the constructor.  However, it has to be done with a very simple twist:  even if many Deck objects are constructed in a given program, this static method will not allow itself to be executed more than once.  Since masterPack[] is a static, unchanging, entity, it need not be built every time a new Deck is instantiated.  So this method needs to be able to ask itself, "Have I been here before?", and if the answer is "yes", it will immediately return without doing anything;  it has already built masterPack[] in a previous invocation.

**Comment by hmason55** [comment]
I will be able to work on the Deck class for this project, if anyone else would like to work with me just let me know and we can divide up the methods.

**Comment by mdoussias** [comment]
I can do some work on the deck class as well tomorrow.  So any methods you want to leave to me, please go ahead.

**Comment by hmason55** [comment]
I was thinking of working on the shuffle, init, and default constructor methods this weekend. That would leave allocateMasterPack, inspectCard, and dealCard methods if you want to start those.

**Comment by mdoussias** [comment]
cool... I will work on 
allocateMasterPack() 
inspectCard() and 
dealCard()

I expect to have done by end of day, 03-18-17

**Comment by mdoussias** [comment]
Just typing this here so I don't forget.... I may have made a mistake in the notes of card class, not realizing that 1 == A.....

**Comment by hmason55** [comment]
@mdoussias Alright, I've finished my section. It should be all good to go for your methods!

**Comment by hmason55** [comment]
The Deck class is working well so far, let me know if there are any other problems with it but for now I'm going to close the issue. All that's left for this one is formatting and commenting.
