### ISSUE TITLE
Main Class

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/p12345vls-Decks-of-Cards#3]
We will need a main class that will call and test the [Hand]( https://github.com/team-makeSmart/p12345vls-Decks-of-Cards/blob/master/Hand.java ), [Deck]( https://github.com/team-makeSmart/p12345vls-Decks-of-Cards/blob/master/Deck.java ), and [Card]( https://github.com/team-makeSmart/p12345vls-Decks-of-Cards/blob/master/Card.java ) classes.

> It is now time to allow your Deck class to interact with your Hand class.  Don't add anything to the two classes, but do everything in this phase from within your main() client.

> Ask the user (interactively) to select the number of players (a number from 1 to 10).  That's one question, one numeric answer, and no further user-interaction.  Once you have validated a legal value, instantiate a single-pack Deck object without shuffling, deal a deck into that many Hand objects, dealing all cards until the deck is empty.  Since the number of players chosen by the user may not divide evenly into 52, the number of cards dealt into the various hands might differ, but only by, at most, one.  Display all the hands after the deal. 

> Reset the objects to their initial state, but this time shuffle the deck before a second deal (same # of players).

> To be clear, dealing to hands means dealing a single card to each hand, until all hands have one card, then repeating to give all hands a second card, etc., until the cards are gone, and each hand has (nearly) the same number of cards.  It does not mean dealing x cards to one hand, then x to the next hand, etc.  This is very important.

**Comment by mdoussias** [comment]
We are to make one file, so I uploaded that as Assig3.java to dump all the classes into once they are done.
We can later convert to .txt for a final submission document.

**Comment by hmason55** [comment]
I don't know how many of us are currently editing the Assig3.java file so I've just been updating the Deck class in its own file. Feel free to move the updated methods from there to the Assig3.java file when we're ready since that's what we are turning in.

**Comment by mdoussias** [comment]
I've been working on the assig3 file.

**Comment by mdoussias** [comment]
I put up two pull requests but I am going to take a break for now, if you want to see my pull requests and work on assig3... I'll send an email out as well
