### ISSUE TITLE
Quality Check

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/p12345vls-Decks-of-Cards#4]
Make sure all code is working correctly before turn in and test all requirements in the assignment specifications.

**The following classes work correctly and are ready for turn in:**
- [ ] Main
- [ ] Deck
- [ ] Hand
- [ ] Card

**Comment by p12345vls** [comment]
Hand and Card tested and work correctly, outputs are right, according to assignment specification. However, the clone method can be omitted.

**Comment by p12345vls** [comment]
Both, Hand and Card class need to be formatted correctly (format indentation). Both however are tested and work correctly. The main methods from both classes can be moved in a separated file.

**Comment by hmason55** [comment]
Since we are using Card.VALID_CARD_VALUES as a constant, Deck.allocateMasterPack should be updated to utilize it similar to Card.takeCard.
