### ISSUE TITLE
Add more details to notes at top of files...

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/p12345vls-Decks-of-Cards#5]
Need to add a little more detailed notes to the top of all files so the professor can more easily identify what the files are for....

/*
* Team Member Names:  ..., ..., .... , ...
* Assignment 3, MODULE 3
* Class CST338
*/

**Comment by mdoussias** [comment]
I know this is a simple issue, just testing out how to make an issue... I can handle this later.

**Comment by hmason55** [comment]
Good idea Maco, I forgot about this but it's pretty important.
