### ISSUE TITLE
Card Class 

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/p12345vls-Decks-of-Cards#6]
- [x] The class Card class notes need some fixing to be consistent for spacing and capitalization.  
e.g. (" note" vs "note" vs "Note")
- [ ]  Make detailed notes 
- [x] Test to be sure class works. 
- [x] Card class is written in an order that does not fully follow the order of the spec.  Rearrange card class to follow the order order as given in the spec, respectively.

**Comment by mdoussias** [comment]
I will work on this and submit by end of day 03-17-18

Note: It does not appear as though I need to make any structural changes to the functionality, so it should work the exact same with other classes when I'm done.

**Comment by p12345vls** [comment]
I sent an email earlier this week confirming that that Class Card is tested and work correctly.

**Comment by mdoussias** [comment]
Cool... I checked that off.

**Comment by mdoussias** [comment]
I made the Card class a little more consistent with note style and changed the order to more match the spec.   No change to functionality.
Some areas still exist that may need more commenting.  I did not change them because I did not full understand them.  Primarily the equals() method and the isValid() method.

**Comment by hmason55** [comment]
Seems kind of strange that he doesn't want us to create an enum or final char[] array of valid card values like A, K, Q, J, 10, 9...
I think it would make the Deck constructor much cleaner.

**Comment by mdoussias** [comment]
Yeah, I don't understand the reasoning either. 
But maybe it's just an exercise to test out different ways of thinking of things.  
E.g., we could also do the enum suits as char 'h','d','s','c'

**Comment by mdoussias** [comment]
Also remember that an identifier cannot be a number.  So an enum of 1,2,3,4,5,6,7,8,9,10 probably wouldn't be possible because those are already integer keyword constants

**Comment by p12345vls** [comment]
Enumerated values are constants meaning that they should probably be capitalized?

**Comment by hmason55** [comment]
I think I'm going to make a final char[] for the valid card values and put it in the Deck class, it's getting way too messy without it. We can always change it later if we decide it's not going to work.

**Comment by mdoussias** [comment]
@ P12345vls, I was thinking the same thing.... not sure how we should use capitals or lowercase
@p12345vls, not sure what the @Override is for.... in the Card Class....  should that be outside the notes where it is?
@hmason55, As long as it will meet the spec and make it simpler, I think it will be good.

**Comment by p12345vls** [comment]
We can change enum to capitals later if we want to be consistent with the naming conventions. We override the toString method because it is a method defined in the Object class.

**Comment by p12345vls** [comment]
Every class has Object as a super class. That is, our class inherits the Object class and (Correction) the equals method is also a method of the Object class. ( I thought you mentioned the toString method)

**Comment by hmason55** [comment]
@p12345vls @mdoussias I just updated the Deck class with the final char[] VALID_CARDS, it's what I'm going to use for now but let me know if you think of a better way of doing it. Also if we decide to keep it, we should probably put it in the Card class instead.

**Comment by p12345vls** [comment]
The point is that we will be not consistent with the assignment instructions: 
"A Public enum Type 
Define the Suit enum, { clubs, diamonds, hearts, spades }, inside the Card class. " 
I thing we can check for valid cards just by calling the isValid() from Card class.

**Comment by hmason55** [comment]
@p12345vls Yeah the isValid is fine, I just was concerned about how messy the init method of the Deck class would get without knowing all possible card values. For instance, I made the final char[] which contained the 13 values cards can have so I just loop through them easily. Without that it would be more like this within the Card.Suit loop:

Card ace = new Card('A', suit);
Card two = new Card('2', suit);
Card three = new Card('3', suit);
Card four = new Card('4', suit);
...

cards[x] = ace;
cards[x+1] = two;
cards[x+2] = three;
cards[x+3] = four:
...

Which is kinda messy and also would need a separate counter.

I also think that the Card.Suit enum is fine as is

**Comment by mdoussias** [comment]
@hmason55 I see now more why the final char[] VALID_CARDS is needed.  
I agree this needs to go in the Card class as we can refactor fome of the Card class methods to be a a lot simpler on the boolean expressions.    
We can then inherit that VALID_CARDS constant down to the other classes.

Just to get the basic functionality and a program up and running, I will work with the VALID_CARDS array in the deck class, but eventually we will need to refactor it to be inherited from the Card class.

**Comment by hmason55** [comment]
Sounds good and like I said, we can always change it later to match the
specifications of the assignment if needed.

**Comment by p12345vls** [comment]
We will lose points if we do not much the assignment specifications. We should ask the professor if we are allowed to do so.

**Comment by hmason55** [comment]
@p12345vls That's true, I'll write another init method for the Deck class that follows the specs. I'm just a little surprised that the assignment specs are so overbearing for this one; for instance, I'm also not sure why we aren't using an ArrayList for Deck.cards instead of a Card array.
